export class OdiaSpeechEngine {
    constructor() {
        this.mediaRecorder = null;
        this.audioChunks = [];
        this.isRecording = false;
        
        // 🚨 IMPORTANT FOR TOMORROW: Update this string with your current live Ngrok tunnel URL 
        // generated by Cell 3 in Google Colab. Do not add an end slash '/' to this string.
        this.apiBaseUrl = "https://snugness-reappear-uncivil.ngrok-free.dev"; 
    }

    /**
     * Bootstraps local microphone streams and initializes binary chunk storage arrays.
     */
    async startRecording() {
        try {
            this.audioChunks = []; 
            
            const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
            this.mediaRecorder = new MediaRecorder(stream);
            
            this.mediaRecorder.ondataavailable = (event) => {
                if (event.data.size > 0) {
                    this.audioChunks.push(event.data);
                }
            };

            this.mediaRecorder.start();
            this.isRecording = true;
            console.log("Audio capturing system initialized.");
        } catch (error) {
            console.error("Hardware streaming fault caught:", error);
            throw error;
        }
    }

    /**
     * Tears down active streaming connections, builds a raw binary file, and routes data to the cloud.
     */
    async stopRecording() {
        return new Promise((resolve, reject) => {
            if (!this.mediaRecorder) {
                reject("No running audio stream instance found.");
                return;
            }

            this.mediaRecorder.onstop = async () => {
                try {
                    // Bundle real-time captured data blocks into standard WAV binary format
                    const audioBlob = new Blob(this.audioChunks, { type: 'audio/wav' });

                    // Append raw payload directly into a virtual network standard form multi-part stream
                    const dataPayload = new FormData();
                    dataPayload.append('file', audioBlob, 'mic_input.wav');

                    // Post multi-part data payload directly through Ngrok tunnel interface targeting FastAPI /transcribe
                    const engineResponse = await fetch(`${this.apiBaseUrl}/transcribe`, {
                        method: 'POST',
                        body: dataPayload
                    });

                    if (!engineResponse.ok) {
                        throw new Error(`Upstream system returned error flag status code: ${engineResponse.status}`);
                    }

                    const structuredResponse = await engineResponse.json();
                    
                    // Return clean transcript string fallback context if empty
                    resolve(structuredResponse.transcript || "କିଛି ଶୁଣାଗଲା ନାହିଁ।"); 
                } catch (error) {
                    console.error("Network communication pipeline fractured:", error);
                    reject(error);
                } finally {
                    // Turn off recording tracks entirely to drop active client microphone usage warning light
                    this.mediaRecorder.stream.getTracks().forEach(track => track.stop());
                    this.isRecording = false;
                }
            };

            this.mediaRecorder.stop();
        });
    }
}
